### ISSUE TITLE
Folders / Groups?

### ISSUE THREAD

**Issue by nicholas-ochoa** [Nikita-Panyuhin/QuickPuTTY#1]
Is it possible to add support for Folders / Groups in the drop down menu?

**Comment by Nikita-Panyuhin** [comment]
I think yes, and this is a great idea. Thank you!
I will try to implement this as soon as possible.

**Comment by Nikita-Panyuhin** [comment]
Implemented in the ["Folders" (1.2.0)](https://github.com/Nikita-Panyuhin/QuickPuTTY/releases/tag/1.2.0) release.
